f_form:
    pattern:  /f/form/
    defaults: { _controller: FormsFormBundle:Form:index }

f_form_new:
    pattern:  /f/form/new/
    defaults: { _controller: FormsFormBundle:Form:new }

f_form_create:
    pattern:  /f/form/create/
    defaults: { _controller: FormsFormBundle:Form:create }

f_form_show:
    pattern:  /f/form/{id}/
    defaults: { _controller: FormsFormBundle:Form:show }

f_form_delete:
    pattern:  /f/form/delete/{id}/
    defaults: { _controller: FormsFormBundle:Form:delete }

f_form_update:
    pattern:  /f/form/update/{id}/
    defaults: { _controller: FormsFormBundle:Form:update }

f_form_edit:
    pattern:  /f/form/{id}/edit/
    defaults: { _controller: FormsFormBundle:Form:edit }


f_formcategory:
    pattern:  /f/formcategory/
    defaults: { _controller: FormsFormBundle:FormCategory:index }

f_formcategory_new:
    pattern:  /f/formcategory/new/
    defaults: { _controller: FormsFormBundle:FormCategory:new }

f_formcategory_create:
    pattern:  /f/formcategory/create/
    defaults: { _controller: FormsFormBundle:FormCategory:create }

f_formcategory_show:
    pattern:  /f/formcategory/{id}/
    defaults: { _controller: FormsFormBundle:FormCategory:show }

f_formcategory_delete:
    pattern:  /f/formcategory/delete/{id}/
    defaults: { _controller: FormsFormBundle:FormCategory:delete }

f_formcategory_update:
    pattern:  /f/formcategory/update/{id}/
    defaults: { _controller: FormsFormBundle:FormCategory:update }

f_formcategory_edit:
    pattern:  /f/formcategory/{id}/edit/
    defaults: { _controller: FormsFormBundle:FormCategory:edit }

