parameters:
#    forms_form.example.class: Forms\FormBundle\Example

services:
#    forms_form.example:
#        class: %forms_form.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
