<?php

namespace Forms\QuestionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TextQuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TextQuestionRepository extends EntityRepository
{
}
