parameters:
#    backend_back.example.class: Backend\BackBundle\Example

services:
#    backend_back.example:
#        class: %backend_back.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
