forms_answer:
    resource: "@FormsAnswerBundle/Resources/config/routing.yml"
    prefix:   /

forms_question:
    resource: "@FormsQuestionBundle/Resources/config/routing.yml"
    prefix:   /

forms_form:
    resource: "@FormsFormBundle/Resources/config/routing.yml"
    prefix:   /

backend_user_nav:
    resource: "@BackendUserNavBundle/Resources/config/routing.yml"
    prefix:   /

backend_back:
    resource: "@BackendBackBundle/Resources/config/routing.yml"
    prefix:   /

front_end_front:
    resource: "@FrontEndFrontBundle/Resources/config/routing.yml"
    prefix:   /

user_user:
    resource: "@UserUserBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"