<?php

namespace Forms\QuestionsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QuestionTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionStyleRepository extends EntityRepository
{
}
