f_textquestion:
    pattern:  /f/textquestion/
    defaults: { _controller: FormsQuestionBundle:TextQuestion:index }

f_textquestion_new:
    pattern:  /f/textquestion/new/
    defaults: { _controller: FormsQuestionBundle:TextQuestion:new }

f_textquestion_create:
    pattern:  /f/textquestion/create/
    defaults: { _controller: FormsQuestionBundle:TextQuestion:create }

f_textquestion_show:
    pattern:  /f/textquestion/{id}/
    defaults: { _controller: FormsQuestionBundle:TextQuestion:show }

f_textquestion_delete:
    pattern:  /f/textquestion/delete/{id}/
    defaults: { _controller: FormsQuestionBundle:TextQuestion:delete }

f_textquestion_update:
    pattern:  /f/textquestion/update/{id}/
    defaults: { _controller: FormsQuestionBundle:TextQuestion:update }

f_textquestion_edit:
    pattern:  /f/textquestion/{id}/edit/
    defaults: { _controller: FormsQuestionBundle:TextQuestion:edit }