f_question:
    pattern:  /f/question
    defaults: { _controller: FormsQuestionBundle:Question:index }

f_question_new:
    pattern:  /f/question/new
    defaults: { _controller: FormsQuestionBundle:Question:new }

f_question_create:
    pattern:  /f/question/create
    defaults: { _controller: FormsQuestionBundle:Question:create }

f_question_show:
    pattern:  /f/question/{id}
    defaults: { _controller: FormsQuestionBundle:Question:show }

f_question_delete:
    pattern:  /f/question/delete/{id}
    defaults: { _controller: FormsQuestionBundle:Question:delete }

f_question_update:
    pattern:  /f/question/update/{id}
    defaults: { _controller: FormsQuestionBundle:Question:update }

f_question_edit:
    pattern:  /f/question/{id}/edit
    defaults: { _controller: FormsQuestionBundle:Question:edit }


f_type:
    pattern:  /f/type
    defaults: { _controller: FormsQuestionBundle:Type:index }

f_type_new:
    pattern:  /f/type/new
    defaults: { _controller: FormsQuestionBundle:Type:new }

f_type_create:
    pattern:  /f/type/create
    defaults: { _controller: FormsQuestionBundle:Type:create }

f_type_show:
    pattern:  /f/type/{id}
    defaults: { _controller: FormsQuestionBundle:Type:show }

f_type_delete:
    pattern:  /f/type/delete/{id}
    defaults: { _controller: FormsQuestionBundle:Type:delete }

f_type_update:
    pattern:  /f/type/update/{id}
    defaults: { _controller: FormsQuestionBundle:Type:update }

f_type_edit:
    pattern:  /f/type/{id}/edit
    defaults: { _controller: FormsQuestionBundle:Type:edit }
