parameters:
#    forms_question.example.class: Forms\QuestionBundle\Example

services:
#    forms_question.example:
#        class: %forms_question.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
