<?php

namespace Forms\FilterBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FormCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormCategoryRepository extends EntityRepository
{
}
