parameters:
#    front_end_front.example.class: FrontEnd\FrontBundle\Example

services:
#    front_end_front.example:
#        class: %front_end_front.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
