<?php

namespace Forms\AnswerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TextARepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TextARepository extends EntityRepository
{
}
