f_answer:
    pattern:  /f/answer
    defaults: { _controller: FormsAnswerBundle:Answer:index }

f_answer_new:
    pattern:  /f/answer/new
    defaults: { _controller: FormsAnswerBundle:Answer:new }

f_answer_create:
    pattern:  /f/answer/create
    defaults: { _controller: FormsAnswerBundle:Answer:create }

f_answer_show:
    pattern:  /f/answer/{id}
    defaults: { _controller: FormsAnswerBundle:Answer:show }

f_answer_delete:
    pattern:  /f/answer/delete/{id}
    defaults: { _controller: FormsAnswerBundle:Answer:delete }

f_answer_update:
    pattern:  /f/answer/update/{id}
    defaults: { _controller: FormsAnswerBundle:Answer:update }

f_answer_edit:
    pattern:  /f/answer/{id}/edit
    defaults: { _controller: FormsAnswerBundle:Answer:edit }
