parameters:
#    backend_form.example.class: Backend\FormBundle\Example

services:
#    backend_form.example:
#        class: %backend_form.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
