<?php

namespace User\GroupBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FosGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FosGroupRepository extends EntityRepository
{
}
