# Routes pour la génération d'un formulaire
elements_text:
    pattern:  /elements/text
    defaults: { _controller: ElementsTextBundle:Text:index }

elements_text_new:
    pattern:  /elements/text/new
    defaults: { _controller: ElementsTextBundle:Text:new }

elements_text_create:
    pattern:  /elements/text/create
    defaults: { _controller: ElementsTextBundle:Text:create }

elements_text_show:
    pattern:  /elements/text/{id}
    defaults: { _controller: ElementsTextBundle:Text/form }

elements_text_delete:
    pattern:  /elements/text/delete/{id}
    defaults: { _controller: ElementsTextBundle:Text:delete }

elements_text_update:
    pattern:  /elements/text/update/{id}
    defaults: { _controller: ElementsTextBundle:Text:update }

elements_text_edit:
    pattern:  /elements/text/{id}/edit
    defaults: { _controller: ElementsTextBundle:Text:edit }
