<?php

namespace Forms\QuestionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QcmQRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QcmQRepository extends EntityRepository
{
}
